services:
  - type: web
    name: portfolio-be
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    env: node
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production